require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sales/v1/sellers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Sales::V1::Seller. As you add validations to Sales::V1::Seller, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Sales::V1::SellersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Sales::V1::Seller.create! valid_attributes
      get sales_v1_sellers_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      seller = Sales::V1::Seller.create! valid_attributes
      get sales_v1_seller_url(seller), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Sales::V1::Seller" do
        expect {
          post sales_v1_sellers_url,
               params: { sales_v1_seller: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Sales::V1::Seller, :count).by(1)
      end

      it "renders a JSON response with the new sales_v1_seller" do
        post sales_v1_sellers_url,
             params: { sales_v1_seller: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Sales::V1::Seller" do
        expect {
          post sales_v1_sellers_url,
               params: { sales_v1_seller: invalid_attributes }, as: :json
        }.to change(Sales::V1::Seller, :count).by(0)
      end

      it "renders a JSON response with errors for the new sales_v1_seller" do
        post sales_v1_sellers_url,
             params: { sales_v1_seller: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sales_v1_seller" do
        seller = Sales::V1::Seller.create! valid_attributes
        patch sales_v1_seller_url(seller),
              params: { sales_v1_seller: new_attributes }, headers: valid_headers, as: :json
        seller.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the sales_v1_seller" do
        seller = Sales::V1::Seller.create! valid_attributes
        patch sales_v1_seller_url(seller),
              params: { sales_v1_seller: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the sales_v1_seller" do
        seller = Sales::V1::Seller.create! valid_attributes
        patch sales_v1_seller_url(seller),
              params: { sales_v1_seller: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sales_v1_seller" do
      seller = Sales::V1::Seller.create! valid_attributes
      expect {
        delete sales_v1_seller_url(seller), headers: valid_headers, as: :json
      }.to change(Sales::V1::Seller, :count).by(-1)
    end
  end
end
